apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 8080  
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
  
    
