apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: employees
    version: v1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
      nodePort: 30001
  selector:
    app: employees
    version: v1
  
  


