apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    labels:
      app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - image: 419810237977.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
        name: mysql-deployment
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ipsa 
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
