apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - image: 419810237977.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
        name: webapp-replicaset
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: 10.244.0.32
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: ipsa

