apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-deployment-v2
    labels:
      app: employees
      version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - image: 419810237977.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.2
        name: webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: 10.244.0.22
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: ipsa
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
