apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30002
  selector:
    app: employees
    version: v2
