apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
    version: v1
spec:
  containers:
  - image: 419810237977.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
    name: webapp
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DBHOST
      value: 10.244.0.4
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: ipsa
